# .goplicate-projects.yaml is used by the "goplicate sync"
# command to run on multiple projects with a single command.

projects:
  - location:
      repository: https://github.com/ilaif/goplicate-example-repo-1
      clone-path: cloned/repo-1
