# A .goplicate.yaml configuration file that tells goplicate
# which "target" files to sync, where to take the "source"
# configurations from, and how to fill parameter values.

targets:
  # goplicate-start:common
  - path: config.yaml
    source:
      path: ./shared/config.yaml
  # goplicate-end:common
sync-config:
  path: .goplicate.yaml
  source:
    path: ./shared/.goplicate.yaml
