# A .goplicate.yaml configuration file that tells goplicate
# which "target" files to sync, where to take the "source"
# configurations from, and how to fill parameter values.

targets:
  - path: .eslintrc.js
    source:
      repository: https://github.com/ilaif/goplicate
      branch: chore/support-remote-git-sources
      path: examples/simple-remote-git/shared-configs-repo/.eslintrc.js
    params:
      - repository: https://github.com/ilaif/goplicate
        branch: chore/support-remote-git-sources
        path: examples/simple-remote-git/shared-configs-repo/params.yaml
