# A .goplicate.yaml configuration file that tells goplicate
# which "target" files to sync, where to take the "source"
# configurations from, and how to fill parameter values.

targets:
  - path: .eslintrc.js
    source:
      repository: https://github.com/ilaif/goplicate-example-shared-configs
      path: .eslintrc.js
    params:
      - repository: https://github.com/ilaif/goplicate-example-shared-configs
        path: params.yaml
