# .goplicate-projects.yaml is used by the "goplicate sync"
# command to run on multiple projects with a single command.

projects:
  - location:
      path: ../simple/repo-1
  - location:
      path: ../simple/repo-2
