# A .goplicate.yaml configuration file that tells goplicate
# which "target" files to sync, where to take the "source"
# configurations from, and how to fill parameter values.

targets:
  # goplicate-start:common
  - path: config.yaml
    source:
      path: ./shared/config.yaml
  - path: new.yaml
    source:
      path: ./shared/new.yaml
    sync-initial: true
  # goplicate-end:common
